// <auto-generated />
using System;
using HotelManagment_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelManagment_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230923125803_AddUsersTable")]
    partial class AddUsersTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelManagment_API.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St",
                            CreatedDate = new DateTime(2023, 9, 23, 15, 58, 3, 590, DateTimeKind.Local).AddTicks(5544),
                            Description = "A wonderful place to stay.",
                            Email = "hotel1@gmail.com",
                            ImageUrl = "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Sample Hotel 1",
                            PhoneNumber = "123-456-7890",
                            Rating = 4.5m
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Elm St",
                            CreatedDate = new DateTime(2023, 9, 23, 15, 58, 3, 590, DateTimeKind.Local).AddTicks(5559),
                            Description = "Another great option for travelers.",
                            Email = "hotel2@gmail.com",
                            ImageUrl = "https://www.travelandleisure.com/thmb/pCU_Y9fbQe4CT5Q73J9k2Bqd_bI=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/header-grand-velas-los-cabos-MXALLINC0222-46d3772ad56f4493a83e1bcb49e119f9.jpg",
                            Name = "Sample Hotel 2",
                            PhoneNumber = "987-654-3210",
                            Rating = 4.0m
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Oak St",
                            CreatedDate = new DateTime(2023, 9, 23, 15, 58, 3, 590, DateTimeKind.Local).AddTicks(5562),
                            Description = "Experience luxury at its finest.",
                            Email = "hotel3@gmail.com",
                            ImageUrl = "https://i0.wp.com/insideflyer.com/wp-content/uploads/2022/09/Review-M-Social-Times-Square-New-York-City-USA-VS-46-scaled.jpeg",
                            Name = "Sample Hotel 3",
                            PhoneNumber = "555-123-4567",
                            Rating = 4.8m
                        },
                        new
                        {
                            Id = 4,
                            Address = "101 Pine St",
                            CreatedDate = new DateTime(2023, 9, 23, 15, 58, 3, 590, DateTimeKind.Local).AddTicks(5564),
                            Description = "Affordable and comfortable accommodations.",
                            Email = "hotel4@gmail.com",
                            ImageUrl = "https://hips.hearstapps.com/clv.h-cdn.co/assets/16/33/3200x2198/gallery-1471831519-iablackhawk.jpg",
                            Name = "Sample Hotel 4",
                            PhoneNumber = "777-999-8888",
                            Rating = 3.7m
                        },
                        new
                        {
                            Id = 5,
                            Address = "321 Cedar St",
                            CreatedDate = new DateTime(2023, 9, 23, 15, 58, 3, 590, DateTimeKind.Local).AddTicks(5566),
                            Description = "A cozy retreat for nature lovers.",
                            Email = "hotel5@gmail.com",
                            ImageUrl = "https://www.wyndhamgrandclearwater.com/assets/images/escape-clearwater.png",
                            Name = "Sample Hotel 5",
                            PhoneNumber = "222-555-1111",
                            Rating = 4.2m
                        });
                });

            modelBuilder.Entity("HotelManagment_API.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelId = 1,
                            IsAvailable = true,
                            PricePerNight = 150.00m,
                            RoomNumber = "101"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelId = 1,
                            IsAvailable = false,
                            PricePerNight = 175.00m,
                            RoomNumber = "102"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelId = 1,
                            IsAvailable = false,
                            PricePerNight = 130.00m,
                            RoomNumber = "103"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelId = 2,
                            IsAvailable = false,
                            PricePerNight = 150.00m,
                            RoomNumber = "Standard double room"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelId = 2,
                            IsAvailable = true,
                            PricePerNight = 500.00m,
                            RoomNumber = "Deluxe sea view suite"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelId = 3,
                            IsAvailable = true,
                            PricePerNight = 100.00m,
                            RoomNumber = "202A"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelId = 4,
                            IsAvailable = false,
                            PricePerNight = 450.00m,
                            RoomNumber = "200"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelId = 4,
                            IsAvailable = true,
                            PricePerNight = 500.00m,
                            RoomNumber = "201"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelId = 5,
                            IsAvailable = false,
                            PricePerNight = 115.00m,
                            RoomNumber = "Standard single room"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelId = 5,
                            IsAvailable = true,
                            PricePerNight = 200.00m,
                            RoomNumber = "Family room with two beds"
                        });
                });

            modelBuilder.Entity("HotelManagment_API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HotelManagment_API.Models.Room", b =>
                {
                    b.HasOne("HotelManagment_API.Models.Hotel", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("HotelManagment_API.Models.Hotel", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
